### ISSUE TITLE
About https://www.toptal.com/back-end/server-side-io-performance-node-php-java-go

### ISSUE THREAD

**Issue by envision-lab** [bradleypeabody/fulltext#2]
Hello Brad,

I'm reaching out about the "benchmark" you did there: https://www.toptal.com/back-end/server-side-io-performance-node-php-java-go

You should better use PM2 to start the node.js application in cluster mode `pm2 start app.js -i 0` to do this benchmark else please run only one thread for php and java to make this benchmark a bit relevant.

Looking forward you to fix the article or this is bad disinformation.

Regards,

**Comment by bradleypeabody** [comment]
Thanks for the suggestion and I understand your concern.  If you read the article itself you'll see that the purpose was to describe the differences in approach to handling IO in each of the environments.  The benchmarks are only additional information, and as expected how benchmarks are interpreted in terms of what it means for each particular application is the subject of a great deal of debate.  I don't have the time to go back and edit the article every time someone comes up with a suggestion on how to improve it.  I do realize that some people look at the article, scroll down to the graphs and say "see, Go is better!" without any further consideration.  That is unfortunate and I all can say is to tell those people what I tell everyone else: Please read the full article.

If there is a comprehensive set of benchmarks which covers things more completely and fairly and can act as a replacement, please let me know and I can add a link and a note to that if it actually fills the bill.
